---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-leader-config-secret
  namespace: infra
type: Opaque
stringData:
  leader.yaml: |-
    remote_write:
      - url: https://your-remote-write-endpoint.com
        remote_timeout: 120s
        name: coralogix
        tls_config:
          insecure_skip_verify: true
        authorization:
          type: Bearer
          credentials: credentials
        follow_redirects: true
        enable_http2: true
        queue_config:
          capacity: 10000
          max_shards: 50
          min_shards: 1
          max_samples_per_send: 2000
          batch_send_deadline: 5s
          min_backoff: 30ms
          max_backoff: 5s
        metadata_config:
          send: true
          send_interval: 1m
          max_samples_per_send: 2000